### ISSUE TITLE
Entities display issue on Iphone 

### ISSUE THREAD

**Issue by clanic70** [tdvtdv/ha-tdv-bar#19] opened 2024-06-06 08:30 UTC
After latest HA core update to 2024.6.0, ha-tdv-bar was unable to show all entities correctly. Any advice about that? Thanks a lot !
![image](https://github.com/tdvtdv/ha-tdv-bar/assets/120659369/ff1a6115-29e2-4da7-8d8f-2173acd1c9be)

**Comment by billmichell** [comment] 2024-06-06 23:33
Issue also affects iPad

**Comment by tdvtdv** [comment] 2024-06-07 10:18
Does the problem persist in the latest release (1.2.2)?

**Comment by clanic70** [comment] 2024-06-07 11:19
Yes, exactly the same 😞

**Comment by Kasttolo** [comment] 2024-06-08 20:35
I have the same problem on Android (TabS9+ and S22)

**Comment by borodaemon** [comment] 2024-06-09 01:58
Also on PC

**Comment by elec2** [comment] 2024-06-09 07:50
PC+Chrome here too, but not all the time, and it seams like it has nothing to do with the browser cache. More like a timing/loading/rendering thing while drawing the page maybe.

**Comment by elec2** [comment] 2024-06-09 07:53
And this problem is also new and all the time. Seems like it has something to do with the different settings of each card. Some logarithmic some not?!

![image](https://github.com/tdvtdv/ha-tdv-bar/assets/46385991/9ccd3435-6a82-480e-9642-87b8602b9416)

**Comment by MobilityManager** [comment] 2024-06-10 12:15
The issue also occurs on the HA MacOS client v2024.5.1 (2024.688) on a MacBook Pro M1 as well as Intel. Also on the HA iPhone App (v2024.5.1) plus the Safari an Chrome browser.
The Safari browser in the MacBook Pro M1 does give the issue also. The Chrome browser on the MacBook Pro M1 does not give any issues and works without problems.
Maybe this information will help?

**Comment by kdutton1964** [comment] 2024-06-10 13:51
Same stuff, M1 Bad, iPad bad both app and safari and chrome, iPhone bad both app and safari, working properly on Android fire 10 tablet through fullykiosk. Thank you for your fantastic contribution.

**Comment by Thunderf1** [comment] 2024-06-14 09:08
Same here in all devices :(

**Comment by Newevg** [comment] 2024-06-16 07:57
Hi everyone, Yes same here looks as pictured above on all Apple devices ( 2024.6.3 ) Will try to restore from backup for now.

**Comment by tdvtdv** [comment] 2024-06-16 10:11
This is a very strange problem, unfortunately on my devices it is not reproducible and I don't understand what is affecting it.

**Comment by dartfrogdk** [comment] 2024-06-16 15:34
I had the same on my chrome browser on my pc, but i copied the code and moved it to a new card and then the issues was gone

**Comment by Lips2000** [comment] 2024-06-16 15:48
Same issue here.

It runs fine in Microsoft Edge and Firefox on my Intel iMac but it will not display properly in Safari/iPhone/iPad (all updated to current OS.

Additionally, the 'fontcolor' argument does not seem to work when displaying in Edge/Firefox. Always black.

Side note: I think this is awesome and I have been searching for exactly this. Hope it gets resolved and thank you!

**Comment by Kasttolo** [comment] 2024-06-16 16:11
In my case, the card is embedded in a standard dashboard. If card is at position 1 of the dashboard, it shows correctly, if at a position at the end of the dashboard, it is not displayed correctly.

**Comment by furll** [comment] 2024-06-18 09:19
To add on the comment above - my dashboard has 10 cards.
ha-tdv-bar works fine in position 1-5 but breaks on position 6-10.

**Comment by dartfrogdk** [comment] 2024-06-18 09:49
I got also problems again but only with a new card, if i reload browser
they show perfectly, but on my Android phone i cant get them to show

tirs. 18. jun. 2024 11.19 skrev furll ***@***.***>:

**Comment by oreboul** [comment] 2024-06-28 07:50
Issue exists on all browser & plaform for me with V1.2.2. works well if you switch back to 1.2.0 or 1.2.1.

**Comment by Lips2000** [comment] 2024-07-15 18:48
Possible work-around:
COPY your created ha-tdv-bar card that will not display then create a new HORIZONTAL card on your page and PASTE your ha-tdv-bar card all by itself into the horizontal card. Save.
Works on Safari and iPhone.
You can also set two pasted cards next to each which is how I figured this out.

**Comment by kdutton1964** [comment] 2024-07-15 20:15
Worked for Me :). Thk

**Comment by Newevg** [comment] 2024-07-18 02:06
> Possible work-around: COPY your created ha-tdv-bar card that will not display then create a new HORIZONTAL card on your 
That trick worked on almost all of my cards. Thank you. But there were 2 x weird cards - nothing different from others. But nothing seems to fix them. Even adding new cars from scratch.  
I ended up duplicating working card and manually changed Entities and now those sensors work too!
Weird issue but it's now fixed.

Thank you!

**Comment by coalfield** [comment] 2024-07-20 22:35
Unfortunately I am seeing the issue on all browsers and iphone.  In the preview window when configuring it all shows fine, but in lovelace once saved no luck :(  The trick mentioned with the horizontal stack shows the same issue.

**Comment by sfortis** [comment] 2024-07-21 06:13
@tdvtdv A discovery I made is that graphs are displayed normally when the widget is the first in order.

https://www.youtube.com/watch?v=703e88wxeTU

**Comment by coalfield** [comment] 2024-07-21 11:25
> @tdvtdv A discovery I made is that graphs are displayed normally when the widget is the first in order.
> 
> https://www.youtube.com/watch?v=703e88wxeTU

You are correct, that fixes it for me!

**Comment by JAGS77** [comment] 2024-08-01 09:27
> Issue exists on all browser & plaform for me with V1.2.2. works well if you switch back to 1.2.0 or 1.2.1.

It work es for me too

**Comment by sfortis** [comment] 2024-08-01 11:22
Confirmed. 1.2.1 works for me too. Firefox / HA android client.

**Comment by brunoz78** [comment] 2024-08-07 08:25
For me too. 1.2.1 works perfectly. Will this bug be fixed?

**Comment by coalfield** [comment] 2024-08-08 09:21
Yes fixed on 1.2.2 for me too

**Comment by fila612** [comment] 2024-08-10 04:36
in apple environments with safari browser still present :(

**Comment by joselao** [comment] 2024-08-16 22:46
Same for desktop (MAC with Safari) and IOS

**Comment by yiannosi** [comment] 2024-09-11 16:14
Well it partly works:
The graphics now are there but the card is partly covered by the one next to it..

![image](https://github.com/user-attachments/assets/ab7ab98d-0e90-4464-af1b-6a3c29a04eea)

**Comment by oreboul** [comment] 2024-09-13 20:53
Tried v1.2.3, unfortunately still the same issue, switch back to v1.2.1. Thank you for the try  :+1:

**Comment by tdvtdv** [comment] 2024-09-13 20:57
The problem has been fixed in version 1.2.3

**Closed by tdvtdv** 2024-09-13 20:57 UTC
Labels: bug
